package com.model;

public class User {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column user.rec_id
     * 
     * @name recId
     * @type Long
     * @length 19
     * @comment 主键
     * 
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    private Long recId;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column user.name
     * 
     * @name name
     * @type String
     * @length 20
     * @comment 名称
     * 
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column user.password
     * 
     * @name password
     * @type String
     * @length 20
     * @comment 密码
     * 
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    private String password;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column user.rec_id
     *
     * @return the value of user.rec_id
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public Long getRecId() {
        return recId;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column user.rec_id
     *
     * @param recId the value for user.rec_id
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}