package com.model;

public class User {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.rec_id
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    private Long recId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.name
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column user.password
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    private String password;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.rec_id
     *
     * @return the value of user.rec_id
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public Long getRecId() {
        return recId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.rec_id
     *
     * @param recId the value for user.rec_id
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}