package com.dao;

import com.model.User;
import com.model.UserCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDAOImpl extends SqlMapClientDaoSupport implements UserDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public UserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public int countByExample(UserCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("user.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public int deleteByExample(UserCriteria example) {
        int rows = getSqlMapClientTemplate().delete("user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public int deleteByPrimaryKey(Long recId) {
        User key = new User();
        key.setRecId(recId);
        int rows = getSqlMapClientTemplate().delete("user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public void insert(User record) {
        getSqlMapClientTemplate().insert("user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public void insertSelective(User record) {
        getSqlMapClientTemplate().insert("user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public List selectByExample(UserCriteria example) {
        List list = getSqlMapClientTemplate().queryForList("user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public User selectByPrimaryKey(Long recId) {
        User key = new User();
        key.setRecId(recId);
        User record = (User) getSqlMapClientTemplate().queryForObject("user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public int updateByPrimaryKeySelective(User record) {
        int rows = getSqlMapClientTemplate().update("user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Wed Jun 13 23:24:32 CST 2012
     */
    public int updateByPrimaryKey(User record) {
        int rows = getSqlMapClientTemplate().update("user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }
}