package com.dao;

import com.model.User;
import com.model.UserCriteria;
import java.util.List;

public interface UserDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    int countByExample(UserCriteria example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    int deleteByExample(UserCriteria example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    int deleteByPrimaryKey(Long recId);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    void insert(User record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    void insertSelective(User record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    List selectByExample(UserCriteria example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    User selectByPrimaryKey(Long recId);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    int updateByPrimaryKey(User record);
}