package com.dao;

import com.model.User;
import com.model.UserExample;
import java.util.List;

public interface UserDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    int deleteByPrimaryKey(Long recId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    void insert(User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    void insertSelective(User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    List selectByExample(UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    User selectByPrimaryKey(Long recId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    int updateByExampleSelective(User record, UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    int updateByExample(User record, UserExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Sat Jun 09 19:34:32 CST 2012
     */
    int updateByPrimaryKey(User record);
}