package com.dao;

import com.model.User;
import com.model.UserCriteria;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDAOImpl extends SqlMapClientDaoSupport implements UserDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public UserDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public int countByExample(UserCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("user.countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public int deleteByExample(UserCriteria example) {
        int rows = getSqlMapClientTemplate().delete("user.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public int deleteByPrimaryKey(Long recId) {
        User _key = new User();
        _key.setRecId(recId);
        int rows = getSqlMapClientTemplate().delete("user.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public void insert(User record) {
        getSqlMapClientTemplate().insert("user.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public void insertSelective(User record) {
        getSqlMapClientTemplate().insert("user.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public List selectByExample(UserCriteria example) {
        List list = getSqlMapClientTemplate().queryForList("user.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public User selectByPrimaryKey(Long recId) {
        User _key = new User();
        _key.setRecId(recId);
        User record = (User) getSqlMapClientTemplate().queryForObject("user.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public int updateByPrimaryKeySelective(User record) {
        int rows = getSqlMapClientTemplate().update("user.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table user
     *
     * @ibatorgenerated Fri Jun 15 21:31:34 CST 2012
     */
    public int updateByPrimaryKey(User record) {
        int rows = getSqlMapClientTemplate().update("user.updateByPrimaryKey", record);
        return rows;
    }
}